import "./globals.css";
import localFont from 'next/font/local'


const acme = localFont({
  src : "./fonts/acme.ttf",
  variable : "--font-acme",
})

const sourgummy = localFont({
  src : "./fonts/sourgummy.ttf",
  variable : "--font-sourgummy",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${acme.variable} ${sourgummy.variable} antialiased`}

      >
        {children}
      </body>
    </html>
  );
}
